trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: "build"
      projects: "backend/CatchEmAll.sln"
      workingDirectory: "backend"
  - task: DotNetCoreCLI@2
    inputs:
      command: "publish"
      publishWebProjects: false
      projects: "backend/CatchEmAll.WebApi/CatchEmAll.WebApi.csproj"
      workingDirectory: "backend"
