//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.9.4.0 (NJsonSchema v10.3.1.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';

@Injectable({
    providedIn: 'root'
})
export class Service {
    private readonly http: HttpClient;

    constructor(http: HttpClient) {
        this.http = http;
    }

    /**
     * @return Success
     */
    public queries(body: CreateQueryOptions): Observable<void> {
        let url = '/api/queries';
        url = url.replace(/[?&]$/, '');

        const _body = body;

        return this.http.post<void>(url, _body);
    }

}

export interface CreateQueryOptions {
    searchTerm?: string | null;
}